<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>MaisonAura.Feature.BespokeInquiry</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Foundation\GlassMapper\MaisonAura.Foundation.GlassMapper.csproj" />
  </ItemGroup>
</Project>
